from enum import StrEnum


class MeetingState(StrEnum):
    IDLE = "IDLE"
    PREPARING = "PREPARING"
    LOGGING_IN = "LOGGING_IN"
    JOINING = "JOINING"
    WAITING_ROOM = "WAITING_ROOM"
    IN_MEETING = "IN_MEETING"
    LEAVING = "LEAVING"
    PAUSED_HUMAN_INPUT = "PAUSED_HUMAN_INPUT"
    ERROR = "ERROR"


class HumanInputStatus(StrEnum):
    PENDING = "PENDING"
    RESOLVED = "RESOLVED"
    EXPIRED = "EXPIRED"


class SchedulerJobType(StrEnum):
    T_MINUS_3 = "T_MINUS_3"
    T_MINUS_1 = "T_MINUS_1"
    LEAVE = "LEAVE"
    RECOVERY = "RECOVERY"


class OnboardingStep(StrEnum):
    UNIVERSITY_URL = "UNIVERSITY_URL"
    EMAIL = "EMAIL"
    PASSWORD = "PASSWORD"
    TIMEZONE = "TIMEZONE"
    SCHEDULE_INPUT = "SCHEDULE_INPUT"
    SCHEDULE_CONFIRMATION = "SCHEDULE_CONFIRMATION"
    COMPLETED = "COMPLETED"
